global:
  scrape_interval: "15s"
  scrape_timeout: "6s"
  evaluation_interval: "15s"

scrape_configs:
  - job_name: "nodejs-app"
    static_configs:
      - targets:
          - "node-app:3000"
    basic_auth:
      username: "chirag"
      password: "password"
